from django.urls import path


from .views import *

urlpatterns = [
    path('marketData/', market_data),
    path('bullbear/', bullbear),
    path('news/', news),
    path('sendotp/',sendOTP),
    path('checkotp/',verifyOTP),
    path('indices/',indices),
    path('verifyPhone/',verifyPhone),
    path('bankRouting/',getBank),
    path('createBO/',newBO),
    path('checkBO/',verifyBO),
    path('createAccount/',signup),
    path('login/',signin),
    path('sectorwise/',sectorwise),
    path('authorize/',auth),
    path('companyprofile/',companyprofile),
    path('price/',price),
    path('companyNews/',companyNews),
    path('companyFinance/',companyFinance),
    path('SMA50/',SMA50),
    path('EMA50/',EMA50),
    path('MACD/',MACD),
    path('STOCH/',STOCH),
    path('RSI/',RSI),
    path('BB/',BB),
    path('predict/',prediction),
    path('ssltest/',createSSL),
    path('ssl/',ssl),
    path('notices/',getNotices),
    path('addWatchlist/',addWatchlist),
    path('deleteWatchlist/',deleteWatchlist),
    path('selectWatchlist/',selectWatchlist),
    path('depositOTP/',depoOTP),
    path('deposit/',deposit),
    path('withdraw/',withdraw),
    path('deposits/',deplist),
    path('getIPO/',ipolist),
    path('getAppliedIPO/',appliedipolist),
    path('withdraws/',withlist),
    path('takeOrder/',getOrder),
    path('takeIPOOrder/',getIPOOrder),
    path('getUser/',User),
    path('getBalance/',Balance),
    path('getPassword/',Password),
    path('getPending/',Pending),
    path('getTransactions/',Transaction),
    path('getPast/',Past),
    path('getPortfolio/',Portfolio),
    path('cancelOrder/',cancelOrder),
    path('changeOtp/',otpChange),
    path('matchOtp/',otpMatch),
    path('changePass/',Passwordchange)]