# Generated by Django 4.1.6 on 2023-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BO_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('nid', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('father_husband_Name', models.CharField(default='', max_length=100)),
                ('motherName', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(default='', max_length=100)),
                ('passport', models.CharField(blank=True, default='', max_length=100)),
                ('issuePlace', models.CharField(blank=True, default='', max_length=100)),
                ('issueDate', models.DateField(blank=True, default='', max_length=100)),
                ('expiryDate', models.DateField(blank=True, default='', max_length=100)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('tin', models.CharField(blank=True, default='', max_length=100)),
                ('cycle', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('division', models.CharField(default='', max_length=100)),
                ('postalCode', models.CharField(default='', max_length=100)),
                ('bankRoutingNo', models.CharField(default='', max_length=100)),
                ('bankAccountNo', models.CharField(default='', max_length=100)),
                ('nominee', models.BooleanField(default='', max_length=100)),
                ('numberOfNominee', models.IntegerField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Investor_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
